name: ci-frontend

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**.js'
  

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up a Node.js environment using the specified node version.
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Install the dependencies.
      # - run: 
      # Run the tests.
      # Install the dependencies.
      - name: dependencies
        run: cd backend && npm ci
      # Run the linter.
      - name: linter
        run: cd backend && npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up a Node.js environment using the specified node version.
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Install the dependencies.
      # - run: 
      # Run the tests.
      # Install the dependencies.
      - name: dependencies
        run: cd backend && npm ci
        
      - name: test
        run: cd backend && npm test
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: build project
        run: echo "build"
        